"use strict";
// import "./matrix-constructor.spec.ts";
// import "./is-matrix.spec.ts";
// import "./random-matrix.spec.ts";
// import "./zeros.spec.ts";
// import "./identity-like.spec.ts";
// import "./get-block.spec.ts";
// import "./set-block.spec.ts";
// import "./get-row.spec.ts";
// import "./set-row.spec.ts";
// import "./exchange-rows.spec.ts";
// import "./exchange-columns.spec.ts";
// import "./get-diagonal.spec.ts";
// import "./to-diagonal-matrix.spec.ts";
// import "./append-block-right.spec.ts";
// import "./append-block-bottom.spec.ts";
// import "./transpose.spec.ts";
// import "./is-equal-to.spec.ts";
// import "./is-less-than.spec.ts"
// import "./is-less-than-or-equal.spec.ts";
// import "./is-greater-than.spec.ts";
import "./is-greater-than-or-equal.spec.ts";
